%% Clear workspace if needed
clear
close all
clc
%% Instantiate APX connection
apx = apxobj();
apx.visible = false;
%% Setup FFT
apx.inputtermination = '100k'; 
apx.windowType = 'Equiripple';
apx.fftLength = 16384;
apx.averages = 10;
%% Setup export 
apx.exportDir = 'C:\Users\Ben\OneDrive\Desktop\work\TUE\matlab codes\BEP\Noise';
%apx.exportFile AUTOGENERATED IF NOT SPECIFIED
%% Execute measurement
apx.runFFT();
%% return data
data = apx.returndata(); %returns PSD FFT SCOPE
%% Plot func (psd vs log(f))
apx.plotPSD();
