%% start here
clear
close all
clc
%% Do job
apx = apxobj();
apx.inputtermination = '100k'; 
apx.windowType = 'Equiripple';
apx.fftLength = 16384;
apx.averages = 10;
apx.visible = false;
apx.exportDir = 'C:\Users\Ben\OneDrive\Desktop\work\TUE\matlab codes\BEP\Noise';
%apx.exportFile AUTOGENERATED IF NOT SPECIFIED
apx.runFFT();
data = apx.returndata(); %returns PSD FFT SCOPE
apx.plotPSD();
